{{- if or .Values.addons.enabled .Values.customAddons }}
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: {{ .Values.clusterName }}-addons
  namespace: {{ include "cluster.namespace" . }}
spec:
  clusterSelector:
    matchLabels:
      {{- if and .Values.addons.enabled .Values.addons.calico }}
      cni: calico
      {{- end }}
      {{- if and .Values.addons.enabled .Values.addons.metrics }}
      metrics-server: "true"
      {{- end }}
      {{- if .Values.customAddons }}
      custom-addons: "true"
      {{- end }}
  resources:
  {{- if and .Values.addons.enabled .Values.addons.calico }}
  - kind: ConfigMap
    name: calico-crs-configmap
  {{- end }}
  {{- if and .Values.addons.enabled .Values.addons.metrics }}
  - kind: ConfigMap
    name: metrics-server-configmap
  {{- end }}
  {{- range .Values.customAddons }}
  - kind: ConfigMap
    name: {{ .name }}-configmap
  {{- end }}
{{- end }}